<?php

namespace Database\Seeders;

use App\Models\Ingredients;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class IngredientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            [
                'name' => 'Farine',
                'image' => 'images/ingredients/flour.jpg',
                'calories' => 364,
                'carbohydrates' => 76,
                'proteins' => 10,
                'fats' => 1,
                'sugars' => 0.4,
                'fiber' => 3.4,
            ],
            [
                'name' => 'Sucre',
                'image' => 'images/ingredients/sugar.jpg',
                'calories' => 387,
                'carbohydrates' => 100,
                'proteins' => 0,
                'fats' => 0,
                'sugars' => 100,
                'fiber' => 0,
            ],
            [
                'name' => 'Levure chimique',
                'image' => 'images/ingredients/baking_powder.jpg',
                'calories' => 0,
                'carbohydrates' => 0,
                'proteins' => 0,
                'fats' => 0,
                'sugars' => 0,
                'fiber' => 0,
            ],
            [
                'name' => 'Sel',
                'image' => 'images/ingredients/salt.jpg',
                'calories' => 0,
                'carbohydrates' => 0,
                'proteins' => 0,
                'fats' => 0,
                'sugars' => 0,
                'fiber' => 0,
            ],
            [
                'name' => 'Œufs',
                'image' => 'images/ingredients/eggs.jpg',
                'calories' => 143,
                'carbohydrates' => 0.6,
                'proteins' => 13,
                'fats' => 9.5,
                'sugars' => 0.6,
                'fiber' => 0,
            ],
            [
                'name' => 'Lait',
                'image' => 'images/ingredients/milk.jpg',
                'calories' => 60,
                'carbohydrates' => 4.7,
                'proteins' => 3.3,
                'fats' => 3.6,
                'sugars' => 5,
                'fiber' => 0,
            ],
            [
                'name' => 'Beurre',
                'image' => 'images/ingredients/butter.jpg',
                'calories' => 717,
                'carbohydrates' => 0.6,
                'proteins' => 0.8,
                'fats' => 81,
                'sugars' => 0.6,
                'fiber' => 0,
            ],
            [
                'name' => 'Poulet',
                'image' => 'images/ingredients/chicken.jpg',
                'calories' => 165,
                'carbohydrates' => 0,
                'proteins' => 31,
                'fats' => 3.6,
                'sugars' => 0,
                'fiber' => 0,
            ],
            [
                'name' => 'Herbes aromatiques',
                'image' => 'images/ingredients/herbs.jpg',
                'calories' => 0,
                'carbohydrates' => 0,
                'proteins' => 0,
                'fats' => 0,
                'sugars' => 0,
                'fiber' => 0,
            ],
            [
                'name' => 'Tomates',
                'image' => 'images/ingredients/tomatoes.jpg',
                'calories' => 18,
                'carbohydrates' => 3.9,
                'proteins' => 0.9,
                'fats' => 0.2,
                'sugars' => 2.6,
                'fiber' => 1.2,
            ],
            [
                'name' => 'Mozzarella',
                'image' => 'images/ingredients/mozzarella.jpg',
                'calories' => 280,
                'carbohydrates' => 2.2,
                'proteins' => 28,
                'fats' => 17,
                'sugars' => 1,
                'fiber' => 0,
            ],
            [
                'name' => 'Basilic',
                'image' => 'images/ingredients/basil.jpg',
                'calories' => 23,
                'carbohydrates' => 2.7,
                'proteins' => 3.2,
                'fats' => 0.6,
                'sugars' => 0.3,
                'fiber' => 1.6,
            ],
            [
                'name' => 'Huile d\'olive',
                'image' => 'images/ingredients/olive_oil.jpg',
                'calories' => 884,
                'carbohydrates' => 0,
                'proteins' => 0,
                'fats' => 100,
                'sugars' => 0,
                'fiber' => 0,
            ],
            [
                'name' => 'Poisson',
                'image' => 'images/ingredients/fish.jpg',
                'calories' => 105,
                'carbohydrates' => 0,
                'proteins' => 22,
                'fats' => 2,
                'sugars' => 0,
                'fiber' => 0,
            ],
            [
                'name' => 'Jus de citron vert',
                'image' => 'images/ingredients/lime_juice.jpg',
                'calories' => 11,
                'carbohydrates' => 4.3,
                'proteins' => 0.4,
                'fats' => 0.1,
                'sugars' => 1.7,
                'fiber' => 0.2,
            ],
            [
                'name' => 'Ail',
                'image' => 'images/ingredients/garlic.jpg',
                'calories' => 149,
                'carbohydrates' => 33,
                'proteins' => 6.4,
                'fats' => 0.5,
                'sugars' => 1,
                'fiber' => 2.1,
            ],
            [
                'name' => 'Cumin en poudre',
                'image' => 'images/ingredients/cumin.jpg',
                'calories' => 375,
                'carbohydrates' => 44,
                'proteins' => 18,
                'fats' => 22,
                'sugars' => 0,
                'fiber' => 10,
            ],
            [
                'name' => 'Tortillas',
                'image' => 'images/ingredients/tortillas.jpg',
                'calories' => 330,
                'carbohydrates' => 57,
                'proteins' => 8,
                'fats' => 8,
                'sugars' => 2,
                'fiber' => 8,
            ],
            [
                'name' => 'Laitue',
                'image' => 'images/ingredients/lettuce.jpg',
                'calories' => 5,
                'carbohydrates' => 1,
                'proteins' => 0.5,
                'fats' => 0.1,
                'sugars' => 0.5,
                'fiber' => 0.5,
            ],
            [
                'name' => 'Salsa',
                'image' => 'images/ingredients/salsa.jpg',
                'calories' => 20,
                'carbohydrates' => 4,
                'proteins' => 1,
                'fats' => 0,
                'sugars' => 2,
                'fiber' => 1,
            ],
            [
                'name' => 'Coriandre fraîche',
                'image' => 'images/ingredients/coriander.jpg',
                'calories' => 23,
                'carbohydrates' => 3.7,
                'proteins' => 2.1,
                'fats' => 0.5,
                'sugars' => 0.9,
                'fiber' => 2.8,
            ],
            [
                'name' => 'Chocolat noir',
                'image' => 'images/ingredients/dark_chocolate.jpg',
                'calories' => 546,
                'carbohydrates' => 31,
                'proteins' => 5.5,
                'fats' => 50,
                'sugars' => 26,
                'fiber' => 10,
            ],
            [
                'name' => 'Beurre fondu',
                'image' => 'images/ingredients/melted_butter.jpg',
                'calories' => 717,
                'carbohydrates' => 0.6,
                'proteins' => 0.8,
                'fats' => 81,
                'sugars' => 0.6,
                'fiber' => 0,
            ],
            [
                'name' => 'Sucre en poudre',
                'image' => 'images/ingredients/powdered_sugar.jpg',
                'calories' => 389,
                'carbohydrates' => 100,
                'proteins' => 0,
                'fats' => 0,
                'sugars' => 100,
                'fiber' => 0,
            ],
        ];

        foreach ($ingredients as $ingredient) {
            $ingredient = new Ingredients($ingredient);
            $ingredient->save();
        }
    }
}
